openapi: 3.0.0
info:
  title: Authentication API
  description: 用户认证相关的API接口
  version: 1.0.0
tags:
  - name: 认证
    description: 用户认证相关操作
paths:
  /public_key:
    get:
      summary: 获取RSA公钥
      description: 返回系统配置的RSA公钥
      tags:
        - 认证
      responses:
        200:
          description: 获取RSA公钥成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "获取RSA公钥成功"
                  data:
                    type: object
                    properties:
                      public_key:
                        type: string
                        example: "RSA公钥字符串"
  /register:
    post:
      summary: 用户注册
      description: 使用手机号和密码注册新用户
      tags:
        - 认证
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - phone
              - password
            properties:
              phone:
                type: string
                description: 手机号
                example: "13800138000"
              password:
                type: string
                description: RSA加密的密码
                example: "加密后的密码字符串"
              username:
                type: string
                description: 用户名
                example: "张三"
      responses:
        200:
          description: 注册成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "注册成功"
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                            example: "a1b2c3d4e5f6"
                          username:
                            type: string
                            example: "张三"
                          phone:
                            type: string
                            example: "13800138000"
                          role:
                            type: integer
                            example: 1
                          status:
                            type: integer
                            example: 1
                          created_at:
                            type: string
                            format: date-time
                            example: "2023-01-01T12:00:00"
                      token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
  /login:
    post:
      summary: 用户登录
      description: 使用手机号和密码登录
      tags:
        - 认证
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - phone
              - password
            properties:
              phone:
                type: string
                description: 手机号
                example: "13800138000"
              password:
                type: string
                description: RSA加密的密码
                example: "加密后的密码字符串"
      responses:
        200:
          description: 登录成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "登录成功"
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
 