openapi: 3.0.0
info:
  title: RSS Feed API
  description: RSS Feed相关的API接口
  version: 1.0.0
tags:
  - name: Feed
    description: RSS Feed相关操作
paths:
  /list:
    get:
      summary: 获取Feed列表
      description: 获取Feed列表，支持分页和筛选
      tags:
        - Feed
      parameters:
        - name: page
          in: query
          description: 页码，默认1
          required: false
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          description: 每页数量，默认20
          required: false
          schema:
            type: integer
            default: 20
        - name: title
          in: query
          description: 标题模糊搜索
          required: false
          schema:
            type: string
        - name: category_id
          in: query
          description: 分类ID
          required: false
          schema:
            type: integer
        - name: is_active
          in: query
          description: 状态(1=启用, 0=禁用)
          required: false
          schema:
            type: integer
            enum: [0, 1]
      responses:
        200:
          description: 获取Feed列表成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "成功"
                  data:
                    type: object
                    properties:
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              example: "a1b2c3d4e5f6"
                            title:
                              type: string
                              example: "科技日报"
                            url:
                              type: string
                              example: "https://example.com/feed.xml"
                            logo:
                              type: string
                              example: "https://example.com/logo.png"
                            description:
                              type: string
                              example: "科技新闻和分析"
                            category_id:
                              type: integer
                              example: 1
                            category_name:
                              type: string
                              example: "科技"
                            is_active:
                              type: boolean
                              example: true
                            article_count:
                              type: integer
                              example: 120
                            last_updated:
                              type: string
                              format: date-time
                              example: "2023-01-01T12:00:00"
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                            example: 100
                          per_page:
                            type: integer
                            example: 20
                          current_page:
                            type: integer
                            example: 1
                          last_page:
                            type: integer
                            example: 5
  /detail:
    get:
      summary: 获取Feed详情
      description: 获取指定Feed的详细信息
      tags:
        - Feed
      parameters:
        - name: feed_id
          in: query
          description: Feed ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: 获取Feed详情成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "成功"
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "a1b2c3d4e5f6"
                      title:
                        type: string
                        example: "科技日报"
                      url:
                        type: string
                        example: "https://example.com/feed.xml"
                      logo:
                        type: string
                        example: "https://example.com/logo.png"
                      description:
                        type: string
                        example: "科技新闻和分析"
                      category_id:
                        type: integer
                        example: 1
                      category_name:
                        type: string
                        example: "科技"
                      is_active:
                        type: boolean
                        example: true
                      article_count:
                        type: integer
                        example: 120
                      last_updated:
                        type: string
                        format: date-time
                        example: "2023-01-01T12:00:00"
                      created_at:
                        type: string
                        format: date-time
                        example: "2023-01-01T10:00:00"
  /add:
    post:
      summary: 添加新Feed
      description: 添加新的RSS Feed
      tags:
        - Feed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - url
                - category_id
              properties:
                title:
                  type: string
                  description: Feed标题
                  example: "科技日报"
                url:
                  type: string
                  description: Feed URL
                  example: "https://example.com/feed.xml"
                logo:
                  type: string
                  description: Logo URL
                  example: "https://example.com/logo.png"
                category_id:
                  type: integer
                  description: 分类ID
                  example: 1
                description:
                  type: string
                  description: 描述信息
                  example: "科技新闻和分析"
      responses:
        200:
          description: 添加Feed成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "添加Feed成功"
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "a1b2c3d4e5f6"
                      title:
                        type: string
                        example: "科技日报"
                      url:
                        type: string
                        example: "https://example.com/feed.xml"
                      logo:
                        type: string
                        example: "https://example.com/logo.png"
                      category_id:
                        type: integer
                        example: 1
                      is_active:
                        type: boolean
                        example: true
                      created_at:
                        type: string
                        format: date-time
                        example: "2023-01-01T12:00:00"
  /update:
    post:
      summary: 更新Feed信息
      description: 更新现有Feed的信息
      tags:
        - Feed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - feed_id
              properties:
                feed_id:
                  type: string
                  description: Feed ID
                  example: "a1b2c3d4e5f6"
                title:
                  type: string
                  description: 新标题
                  example: "科技日报更新版"
                url:
                  type: string
                  description: 新URL
                  example: "https://example.com/feed_new.xml"
                logo:
                  type: string
                  description: 新Logo
                  example: "https://example.com/new_logo.png"
                category_id:
                  type: integer
                  description: 新分类ID
                  example: 2
                description:
                  type: string
                  description: 新描述
                  example: "更新后的科技新闻和分析"
      responses:
        200:
          description: 更新Feed成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "更新Feed成功"
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "a1b2c3d4e5f6"
                      title:
                        type: string
                        example: "科技日报更新版"
                      url:
                        type: string
                        example: "https://example.com/feed_new.xml"